#!/bin/bash

START_PATH=""
LOOKUP_SVN=0
RECURSIVE=0
GO_DEEPER=1

function displayUsage {
    echo "Usage: $0 [OPTIONS]"
    echo "    Valid options are:"
    echo "    -a | --all"
    echo "        Same as --recursive --svn"
    echo "    -r | --recursive"
    echo "        Searches in subfolders recursively"
    echo "    -s | --svn"
    echo "        Searches also for changes in SVN repositories"
    echo "    -h | --help"
    echo "        Displays this help"
    exit 0
}

function evaluateCurrentFolder {
if [ -e ".git" ]; then
    gitStatusMessage=`git status -s`
    if [ ! "x$gitStatusMessage" == "x" ]; then
        echo "[GIT] "`pwd`
        git status -s 2> /dev/null
        echo
        GO_DEEPER=0
    fi
fi
if [ "$LOOKUP_SVN" == 1 ]; then
    if [ -e ".svn" ]; then
        svnStatusMessage=`svn st`
        if [ ! "x$svnStatusMessage" == "x" ]; then
            echo "[SVN] "`pwd`
            svn st 2> /dev/null
            echo
            GO_DEEPER=0
        fi
    fi
fi
}

function searchSubfolders {
for FOLDER in *
do
    if [ -d "$FOLDER" ]; then
        cd "./${FOLDER}"
        evaluateCurrentFolder
        if [ "$RECURSIVE" == 1 ]; then
            if [ "$GO_DEEPER" == 1 ]; then
                searchSubfolders
            else
                GO_DEEPER=1
            fi
        fi
        cd ..
    fi
done
}

function checkPath {
    if [ -d "$START_PATH" ]; then
        echo "Searching in $START_PATH"
    else
        echo "No such file or file is no directory: $START_PATH"
        exit 1
    fi
}


while getopts "hasrp:" optArg; do
    case "$optArg" in
        h)
            displayUsage
            ;;
        s)
            LOOKUP_SVN=1
            ;; 
        p)
            START_PATH="$OPTARG"
            checkPath
            cd "$START_PATH"
            ;; 
        r)
            RECURSIVE=1
            ;; 
        a)
            LOOKUP_SVN=1
            RECURSIVE=1
            ;;
    esac
done
evaluateCurrentFolder
searchSubfolders
